name: Caching Workflow

on:
  workflow_call:
    inputs:
      cache-key:
        required: true
        type: string
      restore-key:
        required: true
        type: string

jobs:
  restore-and-output:
    runs-on: ubuntu-latest
    steps:
      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: ./cache
          key: ${{ inputs.cache-key }}
          restore-keys: |
            ${{ inputs.restore-key }}
      
      - name: Output all files to stdout
        run: |
          find ./cache -type f -exec cat {} \;
